# Generated by Django 4.1.3 on 2022-11-30 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('functionalities', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='functionalities',
            options={'verbose_name_plural': 'Functions'},
        ),
    ]
